name: C++ Project Template Image Builder

# On every push this script is executed
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions: write-all

jobs:
  build:
    name: Build The C++ Project Template project
    runs-on: ubuntu-latest
    steps:
      - name: checkout_master
        uses: actions/checkout@v4
      - name: build_the_production_image
        run: |
          chmod +x run.sh
          ./run.sh -pb -amd64
      - name: Deploy to Somewhere
